name: "Ignition view.json Lint"
description: "Action to lint ignition view.json files"
author: "Eric Knorr"

inputs:
  files:
    description: "Space-separated list of ignition files to lint"
    required: true

branding:
  icon: "zap"
  color: "yellow"

runs:
  using: "composite"
  steps:
    - name: Lint ignition bad view.json files
      run: |
        python ${{ github.action_path }}/src/lint-ignition-views.py ${{ inputs.files }}
      shell: bash
      env:
        INPUT_FILES: ${{ inputs.files }}
