name: "Ignition Lint"
description: "Action to lint ignition view.json files"
author: "Eric Knorr"

inputs:
  files:
    description: "Comma-separated list of ignition files to lint"
    required: false
  component_style:
    description: "Naming convention style for components"
    required: false
  parameter_style:
    description: "Naming convention style for parameters"
    required: false
  component_style_rgx:
    description: "Regex pattern for naming convention style of components"
    required: false
  parameter_style_rgx:
    description: "Regex pattern for naming convention style of parameters"
    required: false
  allow_acronyms:
    description: "Allow acronyms in component and parameter names"
    required: false
    default: "false"

branding:
  icon: "zap"
  color: "orange"

runs:
  using: "composite"
  steps:
    - name: Lint ignition view.json files
      run: |
        python ${{ github.action_path }}/src/ignition_lint.py \
          --files "${{ inputs.files }}" \
          --component-style "${{ inputs.component_style }}" \
          --parameter-style "${{ inputs.parameter_style }}" \
          --component-style-rgx "${{ inputs.component_style_rgx }}" \
          --parameter-style-rgx "${{ inputs.parameter_style_rgx }}"
          --allow-acronyms "${{ inputs.allow_acronyms }}"
      shell: bash
      env:
        INPUT_FILES: ${{ inputs.files }}
        INPUT_COMPONENT_STYLE: ${{ inputs.component_style }}
        INPUT_PARAMETER_STYLE: ${{ inputs.parameter_style }}
        INPUT_COMPONENT_STYLE_RGX: ${{ inputs.component_style_rgx }}
        INPUT_PARAMETER_STYLE_RGX: ${{ inputs.parameter_style_rgx }}
        INPUT_ALLOW_ACRONYMS: ${{ inputs.allow_acronyms }}
