name: Action Integration Test

on:
  push: 

jobs:
  standard-style-test:
    name: Test standard style ignition-lint action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run JSON linting
        uses: ia-eknorr/ignition-lint@feature/prep-v1.1
        with:
          files: tests/cases/PreferredStyle/view.json
          component_style: PascalCase
          parameter_style: camelCase
  regex-style-test:
    name: Test regex style ignition-lint action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run JSON linting
        uses: ia-eknorr/ignition-lint@feature/prep-v1.1
        with:
          files: tests/cases/kebab-case/view.json
          component_style: "^[a-z]+(-[a-z]+)*$"
          parameter_style: "^[a-z]+(-[a-z]+)*$"